server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
      
  datasource:
    driver-class-name: org.h2.Driver
    username: root3
    password: root3
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect    


  application:
    name: RATING-SERVICE  

    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka